baseURL: https://isabelgonzalez-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Isabel Gonzalez
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
 #  subtitle: |-
 #     A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
 #    AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Isabel Gonzalez, I'm an MBA student at LBS
  blog: {}
  contact:
    address: 
      - city: London
        country: UK
        street: Cleveland st
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: isabelg.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (614) 124-0773 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Isabel G
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
       - icon: fa-instagram
         label: Instagram
         url: https://www.instagram.com/isabelglezb/
       - icon: fa-github
         label: GitHub
         url: https://github.com/isabelglezb11
       - icon: fa-linkedin
         label: LinkedIn
         url: https://www.linkedin.com/in/isabelglezb/
  image: JamesTurrell_2
  name: Isabel Gonzalez
  navigation:
    # button1:
      # - name: Get Started
      #   url: blogs
    button2:
      - name: Log In
        url: '#'
    # links:
    #   - name: Home
    #     url: '#'
    #   - name: Blogs
    #     url: blogs
    #   - name: Generic Blog
    #     url: blogs/ipsum
    #   - name: Elements
    #     url: elements.html
    # menu: Menu
    # subtitle: By HTML5 Up
    # title: Forty
  tiles:
    enable: yes
    showcase:
      - image: JamesTurrell_1.jpeg
        subtitle: Wokring with Data Manipulation
        title: Homework One
        url: blogs/homework1.html
      - image: JamesTurrell_2.jpeg
        subtitle: Working with Data Visualisation
        title: Homework Two
        url: blogs/homework2.html
      - image: JamesTurrell_3.jpeg
        subtitle: Working with Data Bases, Web Screping and Shiny App
        title: Homework Three
        url: blogs/homework3.html
      - image: JamesTurrell_4.jpeg
        subtitle: Working with Machine Learning
        title: Homework Four
        url: blogs/homework4.html
      - image: JamesTurrell_5.jpeg
        subtitle: Machine Learning
        title: Team Assignment
        url: blogs/final_group_project.docx
      - image: JamesTurrell_6.jpeg
        subtitle: Isabel's CV
        title: Isabel's Past Experience
        url: blogs/IsabelGonzalezBaca_CV.pdf
  # two:
  #   buttonText: Get Started
  #   enable: yes
  #   subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #     \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
  #     condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #     pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #     Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
  #     amet pharetra et feugiat tempus."
  #   title: Massa libero
  #   url: blogs
